events {}

http {
    server {
        listen 8001;
        location / {
            proxy_pass http://gateway:8001;
            proxy_set_header Host $http_host;
        }
    }

    server {
        listen 8080;
        absolute_redirect off;
        location = /dashboard {
            return 308 /dashboard/;
        }
        location / {
            proxy_pass http://dashboard:80;
            proxy_set_header Host $http_host;
        }
    }

    server {
        listen 9100;
        location / {
            proxy_pass http://mcp-mock:9100;
            proxy_set_header Host $http_host;
        }
    }
}
