"""Exact case contract for Docker Phase 2 evidence."""

from __future__ import annotations

REQUIRED_CASES = (
    # Topology and dependency boundaries.
    "topology_ipv4_no_default_route",
    "topology_ipv6_no_default_route",
    "topology_interlock_app_network_only",
    "topology_proxy_only_upstream_bridge",
    "topology_ipv6_enabled_all_networks",
    "dns_expected_resolution",
    "proxy_expected_destination_port",
    "proxy_wrong_port_denied",
    "postgres_expected_destination_port",
    "postgres_wrong_port_denied",
    "redis_expected_destination_port",
    "redis_wrong_port_denied",
    "squid_policy_parses",
    "squid_malformed_policy_rejected",
    "squid_image_digest_exact",
    "squid_no_tls_interception",
    "squid_via_enabled",
    "disallowed_scheme_denied",
    "disallowed_method_denied",
    "disallowed_port_denied",
    "undeclared_domain_denied",
    # Positive HTTP/TLS controls.
    "allowed_http_through_proxy",
    "allowed_https_connect_through_proxy",
    "allowed_https_original_host",
    "allowed_https_original_sni",
    "allowed_http_via_observed",
    "wrong_hostname_tls_rejected",
    "wrong_hostname_origin_zero_http_requests",
    "untrusted_ca_tls_rejected",
    "untrusted_ca_origin_zero_http_requests",
    "positive_origin_not_block_all_control",
    # Direct bypass attempts from the Interlock image/network.
    "direct_httpx_ipv4_denied",
    "direct_httpx_ipv6_denied",
    "direct_urllib_ipv4_denied",
    "direct_urllib_ipv6_denied",
    "direct_requests_ipv4_denied",
    "direct_requests_ipv6_denied",
    "direct_socket_ipv4_denied",
    "direct_socket_ipv6_denied",
    "direct_curl_ipv4_denied",
    "direct_curl_ipv6_denied",
    # Actual production runtime wiring.
    "runtime_mcp_discovery_proxy",
    "runtime_mcp_tools_call_proxy",
    "runtime_effective_permission_proxy",
    "runtime_effect_readback_proxy",
    "runtime_webhook_proxy",
    "runtime_siem_datadog_proxy",
    "runtime_siem_splunk_proxy",
    "runtime_siem_elastic_proxy",
    "runtime_siem_slack_proxy",
    "runtime_siem_pagerduty_proxy",
    "runtime_siem_generic_proxy",
    "runtime_oidc_jwks_proxy",
    "runtime_ema_jwks_proxy",
    "runtime_provider_openai_proxy",
    "runtime_provider_anthropic_proxy",
    "runtime_provider_google_proxy",
    "runtime_provider_groq_proxy",
    "runtime_groq_sdk_controlled_proxy",
    "runtime_shadow_scanner_proxy",
    "runtime_ollama_enforced_disabled",
    # Ambient-proxy and failure behavior.
    "hostile_HTTP_PROXY_ignored",
    "hostile_HTTPS_PROXY_ignored",
    "hostile_ALL_PROXY_ignored",
    "hostile_NO_PROXY_ignored",
    "hostile_http_proxy_ignored",
    "hostile_https_proxy_ignored",
    "hostile_all_proxy_ignored",
    "hostile_no_proxy_ignored",
    "query_sentinel_exercised",
    "authorization_sentinel_exercised",
    "proxy_credential_sentinel_exercised",
    "proxy_unavailable_no_fallback",
    "dns_timeout_no_fallback",
    "dns_servfail_no_fallback",
    "dns_nxdomain_no_fallback",
    "proxy_credentials_rejected",
    "connect_refusal_no_fallback",
    "tls_failure_no_fallback",
    # Redirect contract.
    "redirect_301_not_followed",
    "redirect_302_not_followed",
    "redirect_303_not_followed",
    "redirect_307_not_followed",
    "redirect_308_not_followed",
    "redirect_cross_host_not_followed",
    "redirect_private_target_not_followed",
    "redirect_raw_ip_not_followed",
    "redirect_downgrade_not_followed",
    "redirect_credentials_not_followed",
    "redirect_loop_not_followed",
    "redirect_hop_exhaustion_not_followed",
    # Destination classes and textual address forms.
    "raw_ipv4_target_denied",
    "raw_ipv6_target_denied",
    "decimal_ipv4_target_denied",
    "octal_ipv4_target_denied",
    "hex_ipv4_target_denied",
    "bracketed_ipv6_target_denied",
    "zone_qualified_ipv6_target_denied",
    "loopback_answer_denied",
    "rfc1918_answer_denied",
    "link_local_answer_denied",
    "metadata_answer_denied",
    "cgnat_answer_denied",
    "multicast_answer_denied",
    "reserved_answer_denied",
    "ula_answer_denied",
    "ipv6_link_local_answer_denied",
    "ipv4_mapped_ipv6_answer_denied",
    "nat64_unsafe_answer_denied",
    "nat64_local_answer_denied",
    "mixed_public_private_answer_denied",
    "mixed_private_public_answer_denied",
    "mixed_ipv4_ipv6_answer_denied",
    # DNS rebinding/cache/retry/concurrency adversaries.
    "public_to_private_rebind_denied",
    "private_to_public_change_denied",
    "ipv4_ipv6_answer_ordering_denied",
    "dns_cache_expiry_rebind_denied",
    "dns_cache_pressure_rebind_denied",
    "dns_cache_eviction_attempt_denied",
    "reconnect_rebind_denied",
    "retry_rebind_denied",
    "concurrent_refresh_rebind_denied",
    "denied_sink_zero_requests",
    # Retained evidence integrity and disclosure.
    "origin_safe_log_fields_only",
    "proxy_safe_log_fields_only",
    "retained_logs_sentinel_free",
    "junit_sentinel_free",
    "manifest_sentinel_free",
)

if len(REQUIRED_CASES) != len(set(REQUIRED_CASES)):
    raise RuntimeError("Phase 2 required case contract contains duplicates")
