import { createPortal } from 'react-dom'
import { Printer, X } from 'lucide-react'
import type { AuditRow } from '../pages/Audit'

interface Props {
  rows: AuditRow[]
  generatedAt: string
  onClose: () => void
}

function fmt(ts: string): string {
  return ts ? new Date(ts).toLocaleString() : '-'
}

// Print preview + artifact for the audit log.
//
// Robustness choices (the previous mount-on-print + @media-visibility approach
// printed blank):
//  - Rendered into a STABLE overlay the user opens before printing, so the doc
//    is committed to the DOM well before window.print() runs (no mount race).
//  - PORTALED to <body> as a sibling of #root. In print we hide #root entirely
//    (display:none) and let this doc flow in normal document flow, so a long
//    table paginates across pages instead of being clipped to page one.
//  - Its own light-on-white surface with HARDCODED #000/#fff colors — never
//    inherits the dark dashboard theme, so suppressed backgrounds can't blank it.
//  - Renders every row (no virtualization, no slicing).
export default function AuditPrintView({ rows, generatedAt, onClose }: Props) {
  return createPortal(
    <div className="audit-print-overlay" onClick={onClose}>
      <div className="audit-print-shell" onClick={e => e.stopPropagation()}>
        <div className="audit-print-actions audit-no-print">
          <button className="btn btn-cyan btn-sm" onClick={() => window.print()}>
            <Printer size={13} />Print / Save PDF
          </button>
          <button className="btn btn-ghost btn-sm" onClick={onClose}>
            <X size={13} />Close
          </button>
        </div>
        <div className="audit-print-doc">
          <div className="audit-print-head">
            <div className="audit-print-brand">INTERLOCK</div>
            <div className="audit-print-title">Audit Log — Runtime Decisions</div>
            <div className="audit-print-meta">
              {rows.length} event{rows.length === 1 ? '' : 's'} · generated {generatedAt}
            </div>
          </div>
          <table className="audit-print-table">
            <thead>
              <tr>
                <th>Timestamp</th>
                <th>Source</th>
                <th>Actor</th>
                <th>Target</th>
                <th>Action</th>
                <th>Severity</th>
                <th>Scan Time</th>
                <th>Reason</th>
              </tr>
            </thead>
            <tbody>
              {rows.map(r => (
                <tr key={r.key}>
                  <td>{fmt(r.timestamp)}</td>
                  <td>{r.source}</td>
                  <td>{r.actor}</td>
                  <td>{r.target}</td>
                  <td>{r.action.toUpperCase()}</td>
                  <td>{r.severity !== '-' ? r.severity.toUpperCase() : '—'}</td>
                  <td>{r.scanTime != null ? r.scanTime + 'ms' : '—'}</td>
                  <td>{r.reason}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="audit-print-foot">
            Generated by Interlock — runtime security gateway for AI agents. Full
            runtime-decision log; {rows.length} row{rows.length === 1 ? '' : 's'} rendered.
          </div>
        </div>
      </div>
    </div>,
    document.body,
  )
}
