"""
Anti-cache headers for responses that must never be stored or shared.

The CI boundary-review endpoint performs an outbound observation and appends
evidence, so it is neither safe nor idempotent at the HTTP level. Attaching
the headers inside the route only covers responses the route itself builds:
a 403 from the scope check, a 429 from the rate limiter, a router-generated
405, and the default 500 are all produced elsewhere. Those are exactly the
responses a shared caching proxy is most likely to store and replay to a
different credential, so the headers are applied by ASGI middleware plus a
server-error handler instead.
"""

from __future__ import annotations

import re
from typing import Iterable, List, Optional, Tuple

from starlette._utils import get_route_path

# Exactly the contract documented in docs/integrations/ci-boundary-review-gate.md.
CACHE_CONTROL = "no-store"
PRAGMA = "no-cache"
EXPIRES = "0"
VARY = "Authorization, X-API-Key, Idempotency-Key"

NO_STORE_HEADERS = {
    "Cache-Control": CACHE_CONTROL,
    "Pragma": PRAGMA,
    "Expires": EXPIRES,
    "Vary": VARY,
}

_MANAGED = frozenset({"cache-control", "pragma", "expires", "vary"})

# scope["path"] is already percent-decoded by the server, and a server id
# containing "/" cannot be addressed as a single path segment anyway.
_BOUNDARY_REVIEW_PATH_RE = re.compile(r"^/mcp/servers/[^/]+/boundary-review$")


def is_boundary_review_path(path: str) -> bool:
    """True for the boundary-review endpoint, whatever the outcome or method."""
    return bool(_BOUNDARY_REVIEW_PATH_RE.match(str(path or "")))


def is_boundary_review_scope(scope) -> bool:
    """Match the path Starlette routes after removing any ASGI root path."""
    return scope.get("type") == "http" and is_boundary_review_path(
        get_route_path(scope)
    )


def merge_vary(existing: Iterable[str]) -> str:
    """Union this endpoint's Vary tokens with whatever the response already set.

    Case-insensitive de-duplication with original order preserved. A wildcard
    is discarded on this one endpoint because the contract requires the
    credential and idempotency selectors to be auditable named tokens.
    """
    tokens: List[str] = []
    seen = set()
    for chunk in list(existing) + [VARY]:
        for raw in str(chunk or "").split(","):
            token = raw.strip()
            if not token:
                continue
            if token == "*":
                # This endpoint's contract requires the three credential-
                # selecting fields to be named exactly once. no-store is the
                # actual storage prohibition; Vary remains explicit evidence.
                continue
            key = token.lower()
            if key in seen:
                continue
            seen.add(key)
            tokens.append(token)
    return ", ".join(tokens)


def apply_to_raw_headers(
    raw_headers: Optional[Iterable[Tuple[bytes, bytes]]],
) -> List[Tuple[bytes, bytes]]:
    """Rewrite an ASGI header list so the anti-cache contract holds exactly once."""
    passthrough: List[Tuple[bytes, bytes]] = []
    existing_vary: List[str] = []
    for name, value in list(raw_headers or []):
        lowered = name.decode("latin-1").lower()
        if lowered == "vary":
            existing_vary.append(value.decode("latin-1"))
            continue
        if lowered in _MANAGED:
            continue
        passthrough.append((name, value))

    passthrough.append((b"cache-control", CACHE_CONTROL.encode("latin-1")))
    passthrough.append((b"pragma", PRAGMA.encode("latin-1")))
    passthrough.append((b"expires", EXPIRES.encode("latin-1")))
    passthrough.append((b"vary", merge_vary(existing_vary).encode("latin-1")))
    return passthrough


class BoundaryReviewNoStoreMiddleware:
    """Pure-ASGI middleware: no BaseHTTPMiddleware, so it also covers responses
    generated by the router and the exception middleware below it."""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if not is_boundary_review_scope(scope):
            await self.app(scope, receive, send)
            return

        async def send_wrapper(message):
            if message.get("type") == "http.response.start":
                message = dict(message)
                message["headers"] = apply_to_raw_headers(message.get("headers"))
            await send(message)

        await self.app(scope, receive, send_wrapper)
